apiVersion: v1
kind: ConfigMap
metadata:
  name: stateful-rebalance-client-config-cc
data:
  application.properties: |-
    consumers.score.client.id=src-ccloud-scores.consumer
    consumers.score.group.id=leaderboard.k8.cg.001
    consumers.score.bootstrap.servers=pkc-qvo1m.us-west-2.aws.confluent.cloud:9092
    consumers.score.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
    consumers.score.auto.offset.reset=earliest
    consumers.score.enable.auto.commit=false
    consumers.score.security.protocol=SASL_SSL
    consumers.score.sasl.mechanism=PLAIN
    consumers.score.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule REQUIRED \
      username="NGDARGEXO2Q6FF3I" \
      password="JcvrZa63/uTYhUFouCzeCVp8fOgPlxP5B/9JAcVMeMTLhn+BvuWinWJslJe0jwXB";
    consumers.score.schema.registry.url=https://psrc-vn38j.us-east-2.aws.confluent.cloud
    consumers.score.schema.registry.basic.auth.credentials.source=USER_INFO
    consumers.score.schema.registry.basic.auth.user.info=RHV23E5ZNOM6FUVF:mvNvmZhLJYufL18I7JPK0TKqKq2yTwL306Uv7IRwxxLOLO/klI5oCovSsPr9ZAow

    consumers.player.client.id=src-ccloud-players.consumer
    consumers.player.group.id=leaderboard.k8.cg
    consumers.player.bootstrap.servers=pkc-qvo1m.us-west-2.aws.confluent.cloud:9092
    consumers.player.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
    consumers.player.auto.offset.reset=earliest
    consumers.player.enable.auto.commit=false
    consumers.player.security.protocol=SASL_SSL
    consumers.player.sasl.mechanism=PLAIN
    consumers.player.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule REQUIRED \
      username="NGDARGEXO2Q6FF3I" \
      password="JcvrZa63/uTYhUFouCzeCVp8fOgPlxP5B/9JAcVMeMTLhn+BvuWinWJslJe0jwXB";
    consumers.player.schema.registry.url=https://psrc-vn38j.us-east-2.aws.confluent.cloud
    consumers.player.schema.registry.basic.auth.credentials.source=USER_INFO
    consumers.player.schema.registry.basic.auth.user.info=RHV23E5ZNOM6FUVF:mvNvmZhLJYufL18I7JPK0TKqKq2yTwL306Uv7IRwxxLOLO/klI5oCovSsPr9ZAow
    
    consumers.product.client.id=src-ccloud-product.consumer
    consumers.product.bootstrap.servers=pkc-qvo1m.us-west-2.aws.confluent.cloud:9092
    consumers.product.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
    consumers.product.auto.offset.reset=earliest
    consumers.product.enable.auto.commit=false
    consumers.product.security.protocol=SASL_SSL
    consumers.product.sasl.mechanism=PLAIN
    consumers.product.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule REQUIRED \
      username="NGDARGEXO2Q6FF3I" \
      password="JcvrZa63/uTYhUFouCzeCVp8fOgPlxP5B/9JAcVMeMTLhn+BvuWinWJslJe0jwXB";
    consumers.product.schema.registry.url=https://psrc-vn38j.us-east-2.aws.confluent.cloud
    consumers.product.schema.registry.basic.auth.credentials.source=USER_INFO
    consumers.product.schema.registry.basic.auth.user.info=RHV23E5ZNOM6FUVF:mvNvmZhLJYufL18I7JPK0TKqKq2yTwL306Uv7IRwxxLOLO/klI5oCovSsPr9ZAow
    
    producers.scorecard.client.id=src-ccloud-scorecard.producer
    producers.scorecard.bootstrap.servers=pkc-qvo1m.us-west-2.aws.confluent.cloud:9092
    producers.scorecard.key.deserializer=org.apache.kafka.common.serialization.LongDeserializer
    producers.scorecard.security.protocol=SASL_SSL
    producers.scorecard.sasl.mechanism=PLAIN
    producers.scorecard.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule REQUIRED \
      username="NGDARGEXO2Q6FF3I" \
      password="JcvrZa63/uTYhUFouCzeCVp8fOgPlxP5B/9JAcVMeMTLhn+BvuWinWJslJe0jwXB";
    producers.scorecard.schema.registry.url=https://psrc-vn38j.us-east-2.aws.confluent.cloud
    producers.scorecard.schema.registry.basic.auth.credentials.source=USER_INFO
    producers.scorecard.schema.registry.basic.auth.user.info=RHV23E5ZNOM6FUVF:mvNvmZhLJYufL18I7JPK0TKqKq2yTwL306Uv7IRwxxLOLO/klI5oCovSsPr9ZAow
    
