apiVersion: v1
kind: ConfigMap
metadata:
  name: leaderboard-scores-schema
data:
  schema: |
    {
      "type": "record",
      "namespace": "io.nermdev.schemas.avro.leaderboards",
      "name": "ScoreEvent",
      "fields": [
        {
          "name": "playerId",
          "type": {
            "type": "long",
            "arg.properties": {
              "range": {
                "min": 1,
                "max": 1000
              }
            }
          }
        },
        {
          "name": "productId",
          "type": {
            "type": "long",
            "arg.properties": {
              "range": {
                "min": 10000,
                "max": 10473
              }
            }
          }
        },
        {
          "name": "score",
          "type": {
            "type": "double",
            "range": {
              "max": 10.0
            }
          }
        },
        {
          "name": "date",
          "type": "string"
        }
      ]
    }
---
apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: leaderboard.scores
spec:
  name: leaderboard.scores-value
  data:
    configRef: leaderboard-scores-schema
    format: avro
  compatibilityLevel: BACKWARD
  schemaRegistryClusterRef:
    name: sr