steps:

  - label: ":one-does-not-simply::k8s: Build prereq resources  :hammer::wrench:"
    commands:
      - kustomize build cfk/0_prereq > /dev/null
    plugins:
      - docker#v5.8.0:
          image: dedovicnermin/pscfk-buildkite:0.0.6
          propagate-uid-gid: true


  - label: ":kafka::k8s: Build deployment / datagen connector :punch::superfly:"
    commands:
      - kustomize build cfk > /dev/null
    plugins:
    - docker#v5.8.0:
        image: dedovicnermin/pscfk-buildkite:0.0.6
        propagate-uid-gid: true

  - label: ":java::maven: Tests :one-does-not-simply:"
    commands:
      - mvn surefire:test
      - mvn failsafe:integration-test
    plugins:
      - docker#v5.8.0:
          image: dedovicnermin/pscfk-buildkite:0.0.6
          propagate-uid-gid: true
        
  - label: ":java::maven: Build Artifact :one-does-not-simply:"
    commands:
      - mvn package
    plugins:
      - docker#v5.8.0:
          image: dedovicnermin/pscfk-buildkite:0.0.6
          propagate-uid-gid: true

