# for monitoring interceptor
---
kind: ConfluentRolebinding
apiVersion: platform.confluent.io/v1beta1
metadata:
  name: leaderboard-client-devwrite-0
  labels:
    principal: client
    role: developerwrite
    cscope: kafka
spec:
  principal:
    name: client
    type: user
  resourcePatterns:
    - name: _confluent-monitoring
      resourceType: Topic
      patternType: LITERAL
  role: DeveloperWrite