apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

commonLabels:
  schema: avro


resources:
  - leaderboard.players.yml
  - leaderboard.products.yml
  - leaderboard.scores.yml
  - leaderboard.scorecards.yml

patches:
  - target:
      group: platform.confluent.io
      version: v1beta1
      kind: KafkaTopic
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3