apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: leaderboard.players
spec:
  replicas: 2
  partitionCount: 5
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default
  configs:
    cleanup.policy: compact

