apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: leaderboard.scorecards
spec:
  replicas: 2
  partitionCount: 5
  kafkaClusterRef:
    name: kafka
  kafkaRestClassRef:
    name: default


