apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  schema: avro


resources:
  - leaderboard.players.yml
  - leaderboard.products.yml
  - leaderboard.scores.yml
  - leaderboard.scorecards.yml
